Added diabetes tutorial sample
liupeirong/MLOpsManufacturing pull request #65
Opened 2021-02-23 15:33 UTC by kuimoani

This sample is a tutorial sample that describes the process of implementing a simple diabetes linear regression code to the AML pipeline for users with no AML experience.

2021-02-26 01:12 UTC, h2floh requested changes
Thanks @kuimoani looks super useful! I changed some wording, please check if you are ok with it. 

The sample folder name is misleading, focus here is the process to migrate existing Machine Learning scripts to be executable with AML pipelines. Related backog is #38 .

How about `samples/wrapping-existing-ml-scripts-tutorial` bit long but then it is more discoverable what you get here. It's not about the diabetes sample.

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/.devcontainer/devcontainer.json
> +// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
Can you please rename the file to `.devcontainer.json` and move it to `samples/diabetes-tutorial`, you need to change the reference to the Dockerfile then as well. In that case it is possible to open the devcontainer over the command `Open Folder in Container...` without loosing git control.

![image](https://user-images.githubusercontent.com/29010283/108940271-6402a900-7696-11eb-9c9a-37562a3b20be.png)

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +This is a sample that guides you through the basic works to use your own machine learning code with Azure ML Pipeline.
```suggestion
This sample guides you how to transform your existing machine learning code to work efficiently with Azure Machine Learning Service Pipelines.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +## Background
```suggestion
## Introduction
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +Here is a virtual scenario. You have a simple diabetes linear regression code using Scikit-learn.
```suggestion
Our fictive scenario will use a simple diabetes linear regression code based on Scikit-learn.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +- How can I use it with Azure ML?
```suggestion
Questions:

- What needs to be done to run the regression on Azure Machine Learning?
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +- What should we do for MLOPS?
```suggestion
- What do we need to do to leverage MLOps features of Azure Machine Learning?
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +We will guide you in a very basic way here.
```suggestion
We will guide you step by step through both answers to these questions. 
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +- git clone this repo
```suggestion
- clone this repo
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +- Open vscode in dev container
Can you please explain the steps to get the devcontainer running in more detail?

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +  $ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
How about preinstall Azure CLI it in the devcontainer? Example can be found [here](https://github.com/liupeirong/MLOpsManufacturing/blob/4248158e05a7f3df4a74ae852382eef999cc3ed8/samples/non-python-preprocess/.devcontainer/image/Dockerfile#L45)

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +When finished, you can see the metrics and have *sklearn_regression_model.pkl* file and *fig.png* graph image in *outputs* folder.
```suggestion
When finished, you should see the metrics, the *sklearn_regression_model.pkl* file and *fig.png* graph image in the *outputs* folder.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +From now on, the long journey to make your code the MLOps begins. The first is to split your code. Your code works well with single file, but you need to fragment it for MLOps implementation.
```suggestion
From now on, the long journey to make your code ready for MLOps begins. The first action is to split your code. Your code works well on your dev environment with single file, but you should fragment it for an optimal MLOps implementation.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +It's up to you to decide how many to split! But now... let's break down into 3 steps: Data Preparation, Train, Register Model. The results of this are in the *src/steps* folder.
```suggestion
It's up to you to decide how detailed you want to split! But for now... let's break down into 3 steps: Data Preparation, Train, Register Model. The resulting scripts are already preprepared in the *src/steps* folder.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +> Most works are to handle parameters with *argparse* and leave logs via *Run.get_context()*. Of course, there's a lot of work to do to use advanced features!
```suggestion
> The most effort for the adaption is to handle parameters with *argparse* and do logging via *Run.get_context()*. Of course, there is additional work to do if you want to use advanced features!
```
Can you list or link to some of the advanced features?

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +Then, You can test if the codes above are running well in your local environment.
```suggestion
So, now you can test if the scripts are running in your local environment.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +Once the csv files, graph file, and pkl file are all created in the outputs folder, you can see that they ran normally!
```suggestion
If the csv files, graph file, and pkl file are all created in the outputs folder, everything completed successfully!
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +- Let's go to your Azure ML workspace!
```suggestion
- Let's go check out your Azure ML workspace!
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +Now let's make sure this code works in Azure. Before set up the MLOps pipeline, it needs to individually test whether if your code works normally in Azure ML.
```suggestion
Now let's make sure this code works in Azure. Before setting up the MLOps pipeline, we can test if your code executes within Azure ML.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +The above is to ensure that only the *src/steps/01_prep_data.py* file is executed through the AML Workspace. This can be done if you want to run a single python file in AML, without the need for MLOp
```suggestion
The above command will execute the *src/steps/01_prep_data.py* file through the AML Workspace. This can be used if you just want to run a single python file in AML, where you don't need a MLOps pipeline.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +This code is also set to `compute_target='local'`  so the compute uses your local computer.
```suggestion
This code sets `compute_target='local'`  so the compute uses your local computer.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +This process can step by step to check if your code works well on Azure ML.
```suggestion
This process can be repeated for each step script, in order to check if it works well together with Azure ML.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +## Step 4. Make MLOps pipeline
```suggestion
## Step 4. Creating the MLOps pipeline
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +Now it's time to create a pipeline. Let's look around the code. */ml_service/pipelines/build_pipeline.py* is a script that builds the AML pipeline.
```suggestion
Now it's time to create a pipeline. Let's have a look at the code */ml_service/pipelines/build_pipeline.py*. This script builds the AML pipeline.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +The above code creates *PipelineData* that transfers data between Pipeline Steps. And *PipelineParameter* can give variables whenever you run the pipeline.
```suggestion
The above code creates *PipelineData* objects which help transfer the input and result data between Pipeline Steps. And *PipelineParameter* can pass additional parameters whenever you run the pipeline.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +> Isn't it similar to the ml_service/run_local_compute.py file above? *PipelineStep* can be connected to each step, but *ScriptRunConfig* can only run a single file. In addition, *PipelineStep* canno
```suggestion
> Isn't it similar to the ml_service/run_local_compute.py file above? *PipelineStep* can be connected to each step, but *ScriptRunConfig* can only run a single file. In addition, *PipelineStep* cannot use `compute_targert='local'`, this is only possible to use in *ScriptRunConfig*. 
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +Because each step is connected by *inputs* and *outputs*, all steps are automatically added to the pipeline even if only one of the steps is added.
Cool! Didn't knew that!

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +Publish your pipeline and add it to *PipelineEndpoint* and publish it.
```suggestion
Publish your pipeline and add a *PipelineEndpoint* to it.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +Lastly, let's run the published pipeline.
```suggestion
Last but not least, let's run the published pipeline.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +You can give the parameters when you run the pipeline. When you execute the code above, you can get a link to the Azure ML Workspace and go to the link to see the progress of the pipeline.
```suggestion
You can pass parameters when you run the pipeline. When you execute the code above, you get a link to the Azure ML Workspace and go to the link to see the progress of the pipeline.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +If it runs well, you can see that each step is running normally as follows:
```suggestion
You can see that each step is running:
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +I introduced the process of moving your existing code to Azure ML Pipeline. This is just the beginning and the most basic step to realize the AML Pipeline.
```suggestion
We introduced a basic process pattern on how to move your existing Machine Learning code to be executed by an Azure ML Pipeline.
```

2021-02-26 01:12 UTC, h2floh commented on samples/diabetes-tutorial/README.md
> +
Can you please add to overview
`What does this sample demonstrate:` see below `This sample ...`
 
`What doesn't this sample demonstrate:` (at least one point e.g. like does not go into the contents of the machine learning scripts.)

similar like [here](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples/non-python-preprocess#overview)

2021-03-03 07:44 UTC, kuimoani commented on samples/diabetes-tutorial/README.md
> +> Most works are to handle parameters with *argparse* and leave logs via *Run.get_context()*. Of course, there's a lot of work to do to use advanced features!
It meant another samples of MLOps Manufacturing.
I think I can leave the link to the samples.

2021-03-03 07:45 UTC, kuimoani commented on samples/diabetes-tutorial/README.md
> +  $ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
good idea!

2021-03-03 07:50 UTC, kuimoani commented on samples/diabetes-tutorial/README.md
> +- Open vscode in dev container
Yes. I think I can give the link explaining about devcontainer.

2021-03-03 07:52 UTC, kuimoani commented on samples/diabetes-tutorial/.devcontainer/devcontainer.json
> +// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
Oh, that's good point. Thanks!

2021-03-04 00:46 UTC, h2floh approved these changes
Thanks @kuimoani !

2021-03-04 00:47 UTC, merged